# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shanalikhan.github.io" # the base hostname & protocol for your site 

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Shan Ali Khan
  avatar: "https://avatars3.githubusercontent.com/u/8774556?v=3&s=460"
  gravatar: "shanalikhan1"
  description: "Coder , Blogger and Teacher" # used by search engines

  # Header and footer text
  header_text: >
     <p> Hi, I'm Shan !
     </p>

     <p>I code, write, speak, promote, learn and listen. I speak all over to whoever will listen.</p>
  header_text_feature_image:
  footer_text: >
   Follow me <a href="http://twitter.com/shan_ali_khan">@shan_ali_khan</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  github: "shanalikhan"
  google_plus:
  instagram:
  linkedin:  "https://pk.linkedin.com/in/shanalikhan"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  "http://stackoverflow.com/users/1931605/shan"
  steam:
  tumblr:
  twitter: "shan_ali_khan"
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-66802275-1"
  disqus_shortname: "shankhanblog"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
