# SITE CONFIGURATION
baseurl: "/blog"
url: "https://adityauser.github.io/"

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Aditya Singh

  avatar: assets/img/avatar.png
  favicon: assets/favicon.ico
  gravatar: # Email MD5 hash
  description: "A website with blog posts and pages" # used by search engines

  # Header and footer text
  header_text: >
     <p>Whatever I want to post :)</p>
     <p>Mostly Deep Learning, Probablity and Statistics </p>
  header_text_feature_image: assets/img/BlackBlue.jpg
  
  # Icons
  rss: false
  email_address: "aditya.singh.mat17@iitbhu.ac.in"
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  gitlab:
  github: "https://github.com/adityauser"
  gitter:
  google_plus:
  instagram:
  linkedin:  https://www.linkedin.com/in/aditya-singh-545727161/
  pinterest:
  reddit: https://www.reddit.com/user/adityauser
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: https://twitter.com/ProbablyAditya
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: true # Enable if using math markup
  search: false # Enable the search feature

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next_post: "Next post"
  str_previous_post: "Previous post"
  str_next_page: "Next"
  str_previous_page: "Prev"
  str_continue_reading: "Continue reading"
  str_javascript_required_disqus: "Please enable JavaScript to view comments."
  str_search_no_results: "No results found."

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
theme: jekyll-theme-type
exclude:
  - Gemfile
  - Gemfile.lock
